// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRuswADN45q1OuvRhen57UHwZitiETk7o',
    appId: '1:989247349486:web:47c1476a5ddc7747d9c9ff',
    messagingSenderId: '989247349486',
    projectId: 'enantly',
    authDomain: 'enantly.firebaseapp.com',
    storageBucket: 'enantly.firebasestorage.app',
    measurementId: 'G-QYTB39RYL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChUgo3K0qamDPv0mLsacfxLijO3rgyL2A',
    appId: '1:989247349486:android:5c2e615f9601edf2d9c9ff',
    messagingSenderId: '989247349486',
    projectId: 'enantly',
    storageBucket: 'enantly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkLJWl5z8c_QrkWIE9cdsAKix-MAyFBgc',
    appId: '1:989247349486:ios:12f106a48bf5220bd9c9ff',
    messagingSenderId: '989247349486',
    projectId: 'enantly',
    storageBucket: 'enantly.firebasestorage.app',
    iosBundleId: 'com.example.evanly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkLJWl5z8c_QrkWIE9cdsAKix-MAyFBgc',
    appId: '1:989247349486:ios:12f106a48bf5220bd9c9ff',
    messagingSenderId: '989247349486',
    projectId: 'enantly',
    storageBucket: 'enantly.firebasestorage.app',
    iosBundleId: 'com.example.evanly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRuswADN45q1OuvRhen57UHwZitiETk7o',
    appId: '1:989247349486:web:81b0ce252a28c721d9c9ff',
    messagingSenderId: '989247349486',
    projectId: 'enantly',
    authDomain: 'enantly.firebaseapp.com',
    storageBucket: 'enantly.firebasestorage.app',
    measurementId: 'G-V7JBZLJFXE',
  );

}